### ISSUE TITLE
Ball speeds IRL differ from speeds seen in soccer

### ISSUE THREAD

**Issue by JNeiger** [RoboJackets/robocup-software#1091]
I think you can simulate this by changing the kick_strength in simradio to a constant and measuring the velocity using the tree tab.

It's off by a factor of ~2

**Comment by JNeiger** [comment]
`vel_vision_bug` is the branch I made that produces these problems. We set the velocity of the kick to 5 in the simradio so any velocity we read should be at 5 m/s. The TestKicker play should just print out the ball velocity while trying to shoot on the goal.

**Comment by chachmu** [comment]
I tested the kick speed from python using `main.ball().pos` and it gave the correct result so I'm pretty sure the positions reported are correct meaning that the issue is somewhere in the actual velocity calculation in c++ which is in [ballFilter.cpp](https://github.com/RoboJackets/robocup-software/blob/6731e7a74d22cfc5b2c6a4c60c4bbdd094e6fc83/soccer/modeling/BallFilter.cpp#L20).

**Comment by ashaw596** [comment]
Yeah theres still a couple different Ball predictions methods. They should be merged at some point. Did you check the speed in the Tree? You can graph the vels.

**Comment by JNeiger** [comment]
I'm 90% sure I checked that and it was giving the wrong values too

**Comment by chachmu** [comment]
As far as I can tell, it is wrong in every single place that the c++ side lists it.

**Comment by chachmu** [comment]
It looks like this issue is caused by the smoothing filter on the ball velocity. By the time the filter starts to reach the velocity of the ball it has decelerated enough that the velocity is much lower than the initial kick speed. This can be fixed either by setting the alpha to 1.0 to remove the smoothing or by completely rewriting the ball filtering and prediction system.

**Comment by ashaw596** [comment]
A better fix would be a smarter filter like a Kalman or particle, but
that's complex. A hack to detect kicks/large changes in velocity combined
with alpha tuning might handle the cases we care about better. Or just the
alpha might be enough to work.

**Comment by JNeiger** [comment]
Fixed by #1227
