### ISSUE TITLE
Per-Line Checkstyle/Pretty

### ISSUE THREAD

**Issue by kylestach** [RoboJackets/robocup-software#1300]
It would be very helpful to use a tool like `clang-format-diff` to only run the formatter on changed _lines_ instead of on all changed _files_. Currently the style checker is useless for large PRs like `comp2019` that touch existing files that may or may not already be properly formatted. Unfortunately, I don't think there's an easy way to integrate this into `stylize` because the tool works by piping the output of git diff into `clang-format-diff` - @justbuchanan, do you have any thoughts?

I've got this set up halfway on my fork (not using stylize, and currently the diff doesn't fail CI but it should), and a sample diff for comp2019 is available at https://circleci.com/gh/kylestach/robocup-software/36.

**Comment by justbuchanan** [comment]
Hi, sorry for the slow reply here. `clang-format-diff` is pretty nifty and does a good job for things like this. It would be possible to integrate this into stylize itself, but since clang is the only stylize-supported formatter that is able to work on diffs (AFAIK), it may not be worth setting it up. Feel free to open a feature request on the stylize repo though.

The biggest issue I remember having with checkstyle and formatting was that the version of `clang-format` on circleci was almost always different than the version of on team member's computers, causing diffs. This is something that `clang-format-diff` will help reduce (because less lines get reformatted), but won't fix.

I'd recommend looking into using a specific version of `clang-format` on circleci and encouraging members to use the same version on their machines.

**Comment by kylestach** [comment]
I found a wrapper someone wrote for yapf to only format diffs (actually just a modified version of clang-format-diff, which is also just a wrapper) and PR'd it in #1302. It works pretty nicely. 

I'll look into getting the clang-format versioning down, although it should be alright as long as everyone is on 18.04.

**Comment by justbuchanan** [comment]
Cool, that's nice that it works for yapf also. I put this on the stylize todo list: https://github.com/justbuchanan/stylize/issues/32. I'm not sure when/if I'll get to it, but it doesn't look too hard to implement and would be a nice feature to have.
