### ISSUE TITLE
Port relevant software info from the wiki to our documentation site

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#149]

**Comment by jgkamat** [comment]
This would be nice to have (because getting all of our information on the docs site is a plus).

Here are some docs to move over:
(Root): https://wiki.robojackets.org/w/RoboCup
https://wiki.robojackets.org/w/RC14IMU
https://wiki.robojackets.org/w/RoboCup_Live_Robot_Execution
https://wiki.robojackets.org/w/RoboCup_Software

To move them over to the docs site, create a markdown file in the `docs` directory of either rc-software or rc-firmware. Here are docs on how to create docs: https://robojackets.github.io/robocup-software/md_doc_Documentation.html

For examples on how to write the markdown, check existing docs in the `docs` folder, or check this [markdown cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)

**Comment by chachmu** [comment]
Jay says this has been ported so I am closing it
