### ISSUE TITLE
Bouncing Pass

### ISSUE THREAD

**Issue by ashaw596** [RoboJackets/robocup-software#259]
I'm not sure if it would work. But if our accuracy is high enough, we could do a chip pass that bounces against the side of our robot into the goal. It would be interesting to try I think. The main thing it might have over actually catching the ball is it would allow legal chip shots(also long as its under 150mm after touching the robot) and would work with a bit more inaccuracy in motion control. (Also interesting, it might also work if it bounces off an opponent robot in a pinch.

All assuming we don't kick the ball too hard and damage the robots of course.

**Comment by justbuchanan** [comment]
Definitely a neat idea, I think I've seen a video of CMU doing this a while back.  I don't know if it would requires less motion control accuracy though since the bounce-off angle on a circular robot requires some pretty precise positioning.  I'd say to wait on trying something like this until we have a good one-touch-pass implementation b/c I think that would have a much better usage.  See my notes on that one (issue #244) for how something could be implemented by passing a custom receiver object (BounceReceiver or something) to the CoordinatedPass tactic.
