### ISSUE TITLE
When the ball is invalid, its comet trail ghosts to (0, 0)

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#360]

**Comment by ashaw596** [comment]
Did this ever get fixed?

**Comment by jgkamat** [comment]
Nope, this is still an issue. To reproduce, drag the ball off the field.

**Comment by rk1998** [comment]
Where can I get started with this issue? Which files should I be looking at?

**Comment by jgkamat** [comment]
I can still reproduce this, so this is a good issue!

I would start looking right here: https://github.com/RoboJackets/robocup-software/blob/33aafebf5ce594e604b2df3fdcda6e41c6f99f77/soccer/FieldView.cpp#L268

This section (right below it) is where we actually draw the ball trail (commenting it out should remove the trail completley): https://github.com/RoboJackets/robocup-software/blob/33aafebf5ce594e604b2df3fdcda6e41c6f99f77/soccer/FieldView.cpp#L281

The logic seems right for me, so you'll need to play around with it a bit and see what you find. Let me know if you're stuck!

I would also reference the QT documentation since we use QT in those functions a lot, such as:
http://doc.qt.io/qt-4.8/qpainterpath.html
http://doc.qt.io/qt-4.8/qpointf.html
