### ISSUE TITLE
Style checking failing when force pushing due to 'master' being out of date.

### ISSUE THREAD

**Issue by jgkamat** [RoboJackets/robocup-software#481]
Not really sure whats causing this, but I think this has to do with diffbase 'master'
[see this](https://circleci.com/gh/RoboJackets/robocup-software/758)

I think our diff-base should be the place where we originally branched from (or a more recent branch point), not the latest master....
[Relevant](https://stackoverflow.com/questions/1527234/finding-a-branch-point-with-git)

A possible fix for this would be to checkout master, pull, then checkout back.

**Comment by jgkamat** [comment]
I don't think this is an issue any more. We'll reopen if we see it again.

**Comment by jgkamat** [comment]
This issue is present again on #499

**Comment by justbuchanan** [comment]
@jgkamat, do you think we can fix this by adding `git fetch origin master:master` to the `SETUP_COMMAND` in `config.docif`?  The git fetch command will pull the latest master branch without checking it out.

**Comment by jgkamat** [comment]
Oh I didn't know we could just do that one command, I'll go ahead and add that.

**Comment by justbuchanan** [comment]
Looks like your fix is failing because of SSH issues.  I SSHd into circle and it looks like they're cloning from github with the `git@` ssh url, which requires an SSH key.  They have one at `~/.ssh/id_circleci_github`, but that isn't visible in docker.  Looks like the easiest fix would be to forward the whole `.ssh` folder into Docker if that's possible.

**Comment by jgkamat** [comment]
Oh, nice, thanks for debugging that! I'll just forward that inside

**Comment by jgkamat** [comment]
circleci has direct links in their ~/.ssh/config, I added a sed to swap those out for relative links

**Comment by justbuchanan** [comment]
Sure thing, that should work.  Can't remember quite how circle has it setup, but you might be able to just copy their key and avoid any potential future breakages if they change their ssh config.

Another thing we should check on once that's fixed is the version of `clang-format` in our image.  We'll probably have to keep it as is since it'll match what the Ubuntu users have, it's just a little unfortunate that it's a few versions behind up-to-date distros (Arch, Debian, OS X).
