### ISSUE TITLE
When playing as the blue team, our robots have yellow comet trails

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#486]

**Comment by jgkamat** [comment]
[this is where the trails are being drawn](https://github.com/RoboJackets/robocup-software/blob/59a87f3a43023338556e83c84a2a4a422bf9c365/soccer/FieldView.cpp#L429)

Last I checked, the obvious fix of changing the colors dosent work, it seems to be a larger issue? (opponents have no comet trails at all, in any scenario). I'm guessing this is because the path is not built correctly, but I'm not sure.

**Comment by justbuchanan** [comment]
It seems that my fix for this didn't quite work...
