### ISSUE TITLE
Add Functional Tests to Soccer

### ISSUE THREAD

**Issue by ashaw596** [RoboJackets/robocup-software#662]
It would be nice since our unit test coverage isn't great to add some functional tests that test basic soccer functionality like stop, start, and basic plays.

**Comment by justbuchanan** [comment]
I think this will require a good amount of changes to `soccer`, but it's definitely a good idea.  We'd probably need to add a "headless" mode to soccer similar to what we have for the simulator so that it can run on circleci without a display.

Somewhat related to https://github.com/RoboJackets/robocup-software/issues/217

**Comment by kylestach** [comment]
This is a duplicate of test framework issues.
