### ISSUE TITLE
Fix ball sense (again)

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#750]
I thought I had it all working as of #698, but there's something wrong.  It may be hardware-related.

**Comment by jjones646** [comment]
Check the resistors on the opposite side of the pcb under the flex cable
headers. I slightly recall one maybe not being there.
On Jun 24, 2016 3:46 AM, "Justin Buchanan" <notifications@github.com> wrote:

I thought I had it all working as of #698
<https://github.com/RoboJackets/robocup-software/pull/698>, but there's
something wrong. It may be hardware-related.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/RoboJackets/robocup-software/issues/750>, or mute the
thread
<https://github.com/notifications/unsubscribe/AHAJqZKcqdmrZoE-E4c4bOrTt3zK9UQnks5qO4tmgaJpZM4I9iiv>
.

**Comment by justbuchanan** [comment]
After realizing that the emitter led was always on (not toggling as it should), we discovered that the corresponding line on the control board was connected to vcc...
