### ISSUE TITLE
Config widget in soccer should have a wider first column

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#760]
The default size is too small, so it has to be dragged wider to see the config variable's name.

**Comment by chachmu** [comment]
According to Matt, the default column widths with QT creator don't always work properly. I tried setting the default width of the columns to 200 which works inside the QT creator display, but when I actually compiled soccer it was the same as before. One alternative is to make the minimum size for the columns be 200 which works but now you can't shrink the Name column any smaller than that. The Name column can still be made larger because it just pushes Value off the screen though.

**Comment by chachmu** [comment]
As a side note, 175 seems like a nice width because it splits the widget exactly in half between Name and Value.
