### ISSUE TITLE
soccer's --noref flag should take effect immediately, not after gui, etc has launched

### ISSUE THREAD

**Issue by justbuchanan** [RoboJackets/robocup-software#765]
As it is now, it responds to a few ref messages before turning off external ref.  This is a problem when we're connected to a network where someone else is running the referee.

**Comment by chachmu** [comment]
I think this problem can be resolved by somehow telling the constructor of MainWindow if we should use an external ref or not. This is somewhat difficult because it is called before processor is constructed so you can't pull the value from there. Is it ok to pass that as an argument of the constructor or are we trying to avoid that?
